project_id = 'personal-finance-401213'
dataset_id = 'gili_eyal_expenses'
monthly_expenses_table_name = 'monthly_expenses_final'
recurring_expenses_table_name = 'recurring_monthly_expenses_final'
date_colum = 'month'